DO $$ BEGIN
  CREATE TYPE "OrderSource" AS ENUM ('ONLINE_QR', 'MANUAL_DASHBOARD', 'WAITER_ENTRY');
EXCEPTION
  WHEN duplicate_object THEN null;
END $$;

ALTER TYPE "PaymentStatus" ADD VALUE IF NOT EXISTS 'PARTIAL';
ALTER TYPE "PaymentStatus" ADD VALUE IF NOT EXISTS 'REFUNDED';
ALTER TYPE "PaymentMethod" ADD VALUE IF NOT EXISTS 'BANK_TRANSFER';

ALTER TABLE "Order" ADD COLUMN IF NOT EXISTS "source" "OrderSource" NOT NULL DEFAULT 'ONLINE_QR';
ALTER TABLE "Order" ADD COLUMN IF NOT EXISTS "amountPaid" DECIMAL(10,2);
ALTER TABLE "Order" ADD COLUMN IF NOT EXISTS "balanceDue" DECIMAL(10,2);
ALTER TABLE "Order" ADD COLUMN IF NOT EXISTS "customerName" TEXT;
ALTER TABLE "Order" ADD COLUMN IF NOT EXISTS "customerPhone" TEXT;
ALTER TABLE "Order" ADD COLUMN IF NOT EXISTS "waiterName" TEXT;
ALTER TABLE "Order" ADD COLUMN IF NOT EXISTS "paidAt" TIMESTAMP(3);

ALTER TABLE "OrderItem" ADD COLUMN IF NOT EXISTS "addedAfterInitialOrder" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "OrderItem" ADD COLUMN IF NOT EXISTS "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE "ActivityLog" ADD COLUMN IF NOT EXISTS "orderId" TEXT;
